// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using otpfeladat.repositories;

#nullable disable

namespace otpfeladat.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("otpfeladat.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fuel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassengerCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Range")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fuel = 0,
                            PassengerCapacity = 4,
                            Range = 250
                        },
                        new
                        {
                            Id = 2,
                            Fuel = 1,
                            PassengerCapacity = 3,
                            Range = 120
                        },
                        new
                        {
                            Id = 3,
                            Fuel = 2,
                            PassengerCapacity = 2,
                            Range = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
